<?php
include "../src/components/admin/header.php";
include "../src/components/admin/nav.php";
?>

<!-- Top Bar (hidden when printing) -->
<div class="flex justify-between items-center bg-[#0D0D0D] p-4 mb-4 rounded-md shadow-lg print:hidden">
  <h2 class="text-xl font-bold text-[#FFD700] uppercase tracking-wide">SALES REPORT</h2>
  <div class="w-10 h-10 bg-gray-700 rounded-full flex items-center justify-center text-white font-bold shadow-md">
    <?php echo strtoupper(substr($_SESSION['user_fname'], 0, 1)); ?>
  </div>
</div>

<!-- Print Button (hidden when printing) -->
<div class="mb-4 print:hidden">
    <button id="printReport" class="cursor-pointer bg-yellow-400 text-black font-bold py-2 px-4 rounded shadow hover:bg-yellow-500 transition-all duration-300">
        Print Report
    </button>
</div>

<!-- Printable Area -->
<div id="printArea" class="p-6 bg-gray-900 text-white rounded-md shadow-md
    print:bg-white print:text-black print:shadow-none print:p-8 print:mx-auto print:my-4 print:max-w-[210mm]">

    <!-- Print Header -->
    <div class="text-center mb-6 print:mb-4">
        <h1 class="text-3xl font-extrabold uppercase print:text-3xl print:font-extrabold">GRILLBOOK</h1>
        <p class="text-sm text-gray-300 print:text-black print:text-base">SALES REPORT</p>
        <!-- <p class="text-sm text-gray-300 print:text-black print:text-base">Date: <?php echo date('F j, Y, g:i a'); ?></p> -->
        <hr class="my-2 border-gray-400 print:border-black">
    </div>

    <!-- Report Summary (Print Only) -->
    <div class="hidden print:flex flex-col sm:flex-row sm:justify-between gap-2 mb-4">
        <div class="text-black">
            <p><strong>Generated by:</strong> <?php echo strtoupper($On_Session[0]['user_fname'] . ' ' .$On_Session[0]['user_lname']); ?></p>
        </div>
        <div class="text-black">
            <p><strong>Total Reservations:</strong> <span id="totalCompleteCount">0</span></p>
        </div>
    </div>

    <!-- Reports Table -->
    <div class="overflow-x-auto print:overflow-visible">
        <table class="min-w-full bg-gray-800 text-white rounded-md shadow-md print:bg-white print:text-black print:shadow-none print:border print:border-black" id="reportTable">
            <thead class="bg-gray-700 print:bg-gray-200">
                <tr>
                    <th class="py-3 px-4 text-left print:border print:border-black">Reservation Code</th>
                    <th class="py-3 px-4 text-left print:border print:border-black">Customer Name</th>
                    <th class="py-3 px-4 text-left print:border print:border-black">Email</th>
                    <th class="py-3 px-4 text-left print:border print:border-black">Table</th>
                    <th class="py-3 px-4 text-left print:border print:border-black">Seats</th>
                    <th class="py-3 px-4 text-left print:border print:border-black">Date & Time</th>
                    <th class="py-3 px-4 text-left print:border print:border-black">Menu Total</th>
                    <th class="py-3 px-4 text-left print:border print:border-black">Promo Total</th>
                    <th class="py-3 px-4 text-left print:border print:border-black">Group Total</th>
                    <th class="py-3 px-4 text-left print:border print:border-black">Grand Total</th>
                </tr>
            </thead>
            <tbody id="reportBody">
                <tr>
                    <td colspan="10" class="py-4 text-center text-gray-400 print:text-black">Loading...</td>
                </tr>
            </tbody>
            <tfoot class="bg-gray-800 text-yellow-400 font-bold print:bg-gray-100 print:text-black print:font-bold">
                <tr>
                    <td colspan="6" class="py-3 px-4 text-right print:text-right">Overall Sales Total:</td>
                    <td id="totalMenu" class="py-3 px-4 print:border print:border-black">₱0.00</td>
                    <td id="totalPromo" class="py-3 px-4 print:border print:border-black">₱0.00</td>
                    <td id="totalGroup" class="py-3 px-4 print:border print:border-black">₱0.00</td>
                    <td id="totalGrand" class="py-3 px-4 print:border print:border-black">₱0.00</td>
                </tr>
            </tfoot>
        </table>
    </div>

</div>

<!-- Print Styles -->
<style>
@media print {
    body * {
        visibility: hidden;
    }

    #printArea, #printArea * {
        visibility: visible;
    }

    #printArea {
        position: absolute;
        left: 0;
        top: 0;
        width: 100%;
        margin: 0;
        padding: 0;
    }

    /* Compact table for print */
    #reportTable {
        width: 100% !important;
        border-collapse: collapse !important;
        color: black !important;
        font-size: 9pt; /* smaller font */
    }

    #reportTable th,
    #reportTable td {
        border: 1px solid black !important;
        padding: 4px 6px !important; /* smaller padding */
        word-break: break-word;
    }

    #reportTable thead {
        background-color: #f0f0f0 !important;
        font-size: 9pt;
    }

    #reportTable tfoot {
        background-color: #e0e0e0 !important;
        font-size: 9pt;
    }

    tr {
        page-break-inside: avoid; /* prevent row split */
    }

    /* Header adjustments */
    #printArea h1 {
        font-size: 16pt !important; /* smaller header */
    }

    #printArea p {
        font-size: 8pt !important;
    }

    /* Hide non-print elements */
    .print\\:hidden {
        display: none !important;
    }
}
</style>


<script>
    // Trigger print
    $('#printReport').click(function() {
        window.print();
    });
</script>

<?php
include "../src/components/admin/footer.php";
?>

<script>
$(document).ready(function() {
    function loadReports() {
        $.ajax({
            url: "../controller/end-points/controller.php",
            method: "GET",
            data: { requestType: "fetch_report" },
            dataType: "json",
            success: function(data) {
                let html = '';
                let totalMenu = 0, totalPromo = 0, totalGroup = 0, totalGrand = 0;
                let totalCount = data.length; // Count of completed reservations

                if(totalCount > 0){
                    data.forEach(res => {
                        html += `<tr class="border-b border-gray-700">
                            <td class="py-2 px-5">${res.reserve_unique_code}</td>
                            <td class="py-2 px-5">${res.user_fname} ${res.user_lname}</td>
                            <td class="py-2 px-5">${res.user_email}</td>
                            <td class="py-2 px-5">${res.table_code}</td>
                            <td class="py-2 px-5">${res.seats}</td>
                            <td class="py-2 px-5">${res.date_schedule} ${res.time_schedule}</td>
                            <td class="py-2 px-5">₱${parseFloat(res.menu_total).toFixed(2)}</td>
                            <td class="py-2 px-5">₱${parseFloat(res.promo_total).toFixed(2)}</td>
                            <td class="py-2 px-5">₱${parseFloat(res.group_total).toFixed(2)}</td>
                            <td class="py-2 px-5 font-bold">₱${parseFloat(res.grand_total).toFixed(2)}</td>
                        </tr>`;

                        totalMenu += parseFloat(res.menu_total);
                        totalPromo += parseFloat(res.promo_total);
                        totalGroup += parseFloat(res.group_total);
                        totalGrand += parseFloat(res.grand_total);
                    });
                } else {
                    html = `<tr><td colspan="10" class="py-4 text-center text-gray-400">No completed reservations found.</td></tr>`;
                    totalCount = 0;
                }

                $('#reportBody').html(html);

                $('#totalMenu').text(`₱${totalMenu.toFixed(2)}`);
                $('#totalPromo').text(`₱${totalPromo.toFixed(2)}`);
                $('#totalGroup').text(`₱${totalGroup.toFixed(2)}`);
                $('#totalGrand').text(`₱${totalGrand.toFixed(2)}`);

                $('#totalCompleteCount').text(totalCount);
            }
        });
    }

    loadReports();
});
</script>
